### PR TITLE
feat: 18 Ministries of Nepal Added

### PR DESCRIPTION
**Pull request by shreekrishnalamichhane**

### CODE REVIEW

**Review by thenishantsapkota — CHANGES_REQUESTED** [review]
Please format the code using prettier!

**Review by thenishantsapkota — APPROVED** [review]
LGTM!

**Comment by thenishantsapkota** [comment]
Please resolve all the merge conflicts @shreekrishnalamichhane 🙏

**Comment by shreekrishnalamichhane** [comment]
You merged the new pr before looking into mine so it is conflicting.
I will close this and create a new pr.

**Pull request closed without merging**
