### PR TITLE
Feat/radio nepal

### PR DESCRIPTION
**Pull request by gaurovgiri**
## What kind of change does this PR introduce? 

- [ ] Bug Fix
- [ ] Documentation change
- [X] Added a new website
- [ ] Other(s)

### CODE REVIEW

**Review by susanhsrestha — APPROVED** [review]
LGTM!

**Review by thenishantsapkota — CHANGES_REQUESTED** [review]

**Comment by thenishantsapkota** [comment]
Also @susanhsrestha, could you please properly review the PRs?

**Comment by susanhsrestha** [comment]
Isn't the formatting okay?

**Comment by thenishantsapkota** [comment]
> Contributor

There's no newline at the end of the file

**Review by thenishantsapkota — CHANGES_REQUESTED** [review]
The code still doesn't look formatted to me!

**Review by thenishantsapkota — APPROVED** [review]
LGTM!
Thank you @gaurovgiri for your contribution!

**Pull request merged**
