### PR TITLE
feat: add madi chitwan and madi sankhuwasabha municipalities official …

### PR DESCRIPTION
**Pull request by drishyakarki**
…websites

## What kind of change does this PR introduce? 

- [ ] Bug Fix
- [ ] Documentation change
- [x] Added a new website
- [ ] Other(s)

### CODE REVIEW

**Review by thenishantsapkota — APPROVED** [review]
LGTM!

**Comment by thenishantsapkota** [comment]
@merge-when-green

**Review by susanhsrestha — APPROVED** [review]
LGTM!

**Review by FroostyCodes — APPROVED** [review]
LGTM

**Review by TheLearneer — APPROVED** [review]
Looks good

**Review by thenishantsapkota — APPROVED** [review]

**Pull request merged**
