### PR TITLE
Added two governmental sites 

### PR DESCRIPTION
**Pull request by ori-on1**
## What kind of change does this PR introduce? 

- [x] Bug Fix
- [x] Documentation change
- [x] Added a new website
- [x] Other(s)

### CODE REVIEW

**Review by susanhsrestha — APPROVED** [review]
LGTM!

**Review by thenishantsapkota — CHANGES_REQUESTED** [review]
Please incorporate latest changes into your branch and arrange all the data alphabetically again!

**Review by thenishantsapkota — APPROVED** [review]
LGTM!

**Comment by thenishantsapkota** [comment]
Thank you for your contribution @ori-on1 !

**Pull request merged**
