### PR TITLE
Department of Drug Administration Added

### PR DESCRIPTION
**Pull request by susanhsrestha**
The website of Department of Drug Administration under Ministry of Health is added.

### CODE REVIEW

**Comment by thenishantsapkota** [comment]
Can you please combine #70 and this PR in the same PR?
Thank you

**Comment by susanhsrestha** [comment]
@thenishantsapkota should I create a new branch and combine the changes and make a PR?

**Comment by thenishantsapkota** [comment]
Yes please, make a new branch combine those changes and open another PR

**Comment by susanhsrestha** [comment]
I've made the necessary changes and opened a [PR](#79)

**Pull request closed without merging**
