### PR TITLE
Added 18 websites

### PR DESCRIPTION
**Pull request by AC17dollars**
Added 18 websites, 7 provincial government, 11 others

### CODE REVIEW

**Review by thenishantsapkota — CHANGES_REQUESTED** [review]
Please change all the data to be in alphabetical order. 🙏

**Comment by AC17dollars** [comment]
I sorted the entries, but git diff might've gotten overwhelmed.

**Review by thenishantsapkota — APPROVED** [review]
LGTM!

**Comment by thenishantsapkota** [comment]
Thank you for your contributions @AC17dollars :partying_face:
Join our [Discord](http://discord.gg/7jwZaa8WDr) to claim your contributors role (if you haven't already) and stay connected with us.
Cheers!

**Pull request merged**
